version: '3.7'

services:
  composer:
    network_mode: "none"
    image: composer:1.6
    volumes:
      - .:/app
    user: ${CURRENT_UID}
    command: composer install --ignore-platform-reqs

  php:
    network_mode: "none"
    build: ./docker/php
    image: mrivera/mrivera/php-jwtverify:7.2
    volumes:
      - .:/app
    working_dir: /app
    command: php verify.php